
// ─── 50 Protocol Fields ────
export const PROTOCOL_FIELDS = [
  { id:"protocol_title_full",                        label:"Protocol Title (Full)",                       category:"Study Identification", type:"text" },
  { id:"protocol_short_title",                       label:"Protocol Short Title / Acronym",              category:"Study Identification", type:"text" },
  { id:"protocol_number",                            label:"Protocol Number",                             category:"Study Identification", type:"text" },
  { id:"protocol_version_and_date",                  label:"Protocol Version & Date",                     category:"Study Identification", type:"text" },
  { id:"ind_number",                                 label:"IND Number (if applicable)",                  category:"Regulatory",           type:"text" },
  { id:"ide_number",                                 label:"IDE Number (if applicable)",                  category:"Regulatory",           type:"text" },
  { id:"study_phase",                                label:"Phase",                                       category:"Study Design",         type:"select", options:["Phase 1","Phase 1b","Phase 2","Phase 2a","Phase 2b","Phase 3","Phase 4","N/A"] },
  { id:"study_type",                                 label:"Study Type",                                  category:"Study Design",         type:"select", options:["Interventional","Observational","Registry","Specimen-only"] },
  { id:"allocation_randomization",                   label:"Allocation / Randomization",                  category:"Study Design",         type:"select", options:["Randomized","Non-randomized"] },
  { id:"blinding_masking",                           label:"Blinding / Masking",                          category:"Study Design",         type:"select", options:["Open-label","Single-blind","Double-blind","Triple-blind"] },
  { id:"control_type",                               label:"Control Type",                                category:"Study Design",         type:"select", options:["Placebo","Active comparator","Standard of care","None"] },
  { id:"primary_objective",                          label:"Primary Objective",                           category:"Study Design",         type:"textarea" },
  { id:"primary_endpoints",                          label:"Primary Endpoint(s)",                         category:"Study Design",         type:"textarea" },
  { id:"secondary_endpoints",                        label:"Key Secondary Endpoint(s)",                   category:"Study Design",         type:"textarea" },
  { id:"target_condition",                           label:"Target Indication / Condition",               category:"Study Population",     type:"text" },
  { id:"population_age_range",                       label:"Population Age Range",                        category:"Study Population",     type:"text" },
  { id:"inclusion_criteria_summary",                 label:"Key Inclusion Criteria",                      category:"Study Population",     type:"textarea" },
  { id:"exclusion_criteria_summary",                 label:"Key Exclusion Criteria",                      category:"Study Population",     type:"textarea" },
  { id:"vulnerable_populations_included",            label:"Vulnerable Populations Included?",            category:"Study Population",     type:"text" },
  { id:"investigational_product_name",               label:"Investigational Product Name",                category:"Study Product",        type:"text" },
  { id:"product_type",                               label:"Product Type",                                category:"Study Product",        type:"select", options:["Drug","Device","Biologic","Combination","Digital therapeutic"] },
  { id:"route_of_administration",                    label:"Route of Administration",                     category:"Study Product",        type:"text" },
  { id:"dose_regimen",                               label:"Dose Level(s) / Regimen",                     category:"Study Product",        type:"text" },
  { id:"storage_conditions",                         label:"Storage Conditions",                          category:"Study Product",        type:"text" },
  { id:"emergency_unblinding_process",               label:"Emergency Unblinding Process",                category:"Study Product",        type:"textarea" },
  { id:"number_of_study_visits",                     label:"Number of Study Visits",                      category:"Procedures",           type:"text" },
  { id:"screening_window_days",                      label:"Screening Window (days)",                     category:"Procedures",           type:"text" },
  { id:"key_procedures_high_level",                  label:"Key Procedures by Visit",                     category:"Procedures",           type:"textarea" },
  { id:"imaging_procedures",                         label:"Imaging Procedures (if any)",                 category:"Procedures",           type:"text" },
  { id:"invasive_procedures",                        label:"Invasive Procedures (if any)",                category:"Procedures",           type:"text" },
  { id:"high_risk_procedures_flag",                  label:"High-Risk Procedures?",                       category:"Risk/Safety",          type:"yesno" },
  { id:"data_monitoring_plan_present",               label:"Data Monitoring Plan Present?",               category:"Risk/Safety",          type:"yesno" },
  { id:"dsmb_present",                               label:"DMC/DSMB Established?",                       category:"Risk/Safety",          type:"yesno" },
  { id:"dsmb_review_frequency",                      label:"DSMB Review Frequency",                       category:"Risk/Safety",          type:"text" },
  { id:"stopping_rules_summary",                     label:"Stopping Rules / Early Termination Criteria", category:"Risk/Safety",          type:"textarea" },
  { id:"sae_reporting_timeline_to_sponsor",          label:"SAE Reporting Timeline to Sponsor",           category:"Risk/Safety",          type:"text" },
  { id:"safety_report_handling",                     label:"Safety Letters / IND Safety Report Handling", category:"Risk/Safety",          type:"textarea" },
  { id:"consent_type",                               label:"Consent Type",                                category:"Consent",              type:"select", options:["Paper","eConsent","Hybrid"] },
  { id:"electronic_signature_used",                  label:"Electronic Signature Used?",                  category:"Consent",              type:"yesno" },
  { id:"identity_verification_method_for_e_consent", label:"Identity Verification for eConsent",         category:"Consent",              type:"text" },
  { id:"reconsent_triggers_summary",                 label:"Re-Consent Triggers",                         category:"Consent",              type:"textarea" },
  { id:"recruitment_methods",                        label:"Recruitment Methods",                         category:"Recruitment",          type:"textarea" },
  { id:"recruitment_material_types",                 label:"Recruitment Materials Types",                 category:"Recruitment",          type:"text" },
  { id:"subject_compensation_amount_and_schedule",   label:"Subject Compensation Amount & Schedule",      category:"Payments to Subjects", type:"text" },
  { id:"subject_reimbursement_types",                label:"Subject Reimbursement Types",                 category:"Payments to Subjects", type:"text" },
  { id:"data_collected_types",                       label:"Data Collected Types",                        category:"Data/Privacy",         type:"textarea" },
  { id:"digital_tools_used",                         label:"Mobile App / Wearable / ePRO Used?",          category:"Data/Privacy",         type:"yesno" },
  { id:"biospecimens_collected",                     label:"Biospecimens Collected?",                     category:"Specimens",            type:"yesno" },
  { id:"future_use_banking_plan",                    label:"Future Use / Banking Plan",                   category:"Specimens",            type:"textarea" },
  { id:"genetic_testing_performed",                  label:"Genetic Testing Performed?",                  category:"Specimens/Genetics",   type:"yesno" },
];